#!/usr/bin/env bash


thisdir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && cd -P "$( dirname "$SOURCE" )" && pwd)"

PROGNAME=$(basename "$0")
warn()  { echo "$PROGNAME: ${@}" 1>&2; }
die()   { warn "${@}"; exit 1; }
dbug()   { test -z $DEBUG || warn "${@}"; }

while getopts 'p:' opt; do
  case "${opt}" in
    p)
      PSWD=$OPTARG;;
    ?)
      echo "$PROGNAME requires -p <password> to execute." >&2
      exit 1;;
  esac
done

if [ $# -lt 1 ]; then
	echo "Usage: $0 -p <password>"
  echo "$PROGNAME requires -p <password> to execute." >&2
	exit 1
fi

# Secret action is currently set to the undoing of of the spoofd_ssh
echo "Admin authenticated! Performing secret action."
chsh -s /bin/ash root
cp $thisdir/sshd_config /etc/ssh/sshd_config
rm -rf $thisdir/sshd_config
rc-service sshd restart
echo "Admin approved secret action complete!"

exit 0